from book import Book

COLS_PER_SEC = 2 # columns per section (book-name and chapter)

DATE_FORMAT = "%d.%m.%Y"

# list of all bible-books
BOOKS = []
BOOKS.append(Book("1 Mos", 50))
BOOKS.append(Book("2 Mos",40))
BOOKS.append(Book("3 Mos", 27))
BOOKS.append(Book("4 Mos", 36))
BOOKS.append(Book("5 Mos",34 ))
BOOKS.append(Book("Jos", 24))
BOOKS.append(Book("Ri", 21))
BOOKS.append(Book("Rut", 4))
BOOKS.append(Book("1 Sam", 31))
BOOKS.append(Book("2 Sam", 24))
BOOKS.append(Book("1 Koe", 22))
BOOKS.append(Book("2 Koe", 25))
BOOKS.append(Book("1 Chr", 29))
BOOKS.append(Book("2 Chr", 36))
BOOKS.append(Book("Esra", 10))
BOOKS.append(Book("Neh", 13))
BOOKS.append(Book("Est", 10))
BOOKS.append(Book("Hi", 42))
BOOKS.append(Book("Ps", 150))
BOOKS.append(Book("Spr", 31))
BOOKS.append(Book("Pred", 12))
BOOKS.append(Book("Hld", 8))
BOOKS.append(Book("Jes", 66))
BOOKS.append(Book("Jer", 52))
BOOKS.append(Book("Klgl", 5))
BOOKS.append(Book("Hes", 48))
BOOKS.append(Book("Dan", 12))
BOOKS.append(Book("Hos", 14))
BOOKS.append(Book("Joel", 4))
BOOKS.append(Book("Am", 9))
BOOKS.append(Book("Obd", 1))
BOOKS.append(Book("Jona", 4))
BOOKS.append(Book("Mi", 7))
BOOKS.append(Book("Nah", 3))
BOOKS.append(Book("Hab", 3))
BOOKS.append(Book("Zef", 3))
BOOKS.append(Book("Hag", 2))
BOOKS.append(Book("Sach", 14))
BOOKS.append(Book("Mal", 3))
BOOKS.append(Book("Mt", 28))
BOOKS.append(Book("Mk", 16))
BOOKS.append(Book("Lk", 24))
BOOKS.append(Book("Joh", 21))
BOOKS.append(Book("Apg", 28))
BOOKS.append(Book("Roem", 16))
BOOKS.append(Book("1 Kor", 16))
BOOKS.append(Book("2 Kor", 13))
BOOKS.append(Book("Gal", 6))
BOOKS.append(Book("Eph", 6))
BOOKS.append(Book("Phil", 4))
BOOKS.append(Book("Kol", 4))
BOOKS.append(Book("1 Thess", 5))
BOOKS.append(Book("2 Thess", 3))
BOOKS.append(Book("1 Tim", 6))
BOOKS.append(Book("2 Tim", 4))
BOOKS.append(Book("Tit", 3))
BOOKS.append(Book("Phlm", 1))
BOOKS.append(Book("Hebr", 13))
BOOKS.append(Book("Jak", 5))
BOOKS.append(Book("1 Petr", 5))
BOOKS.append(Book("2 Petr", 3))
BOOKS.append(Book("1 Joh", 5))
BOOKS.append(Book("2 Joh", 1))
BOOKS.append(Book("3 Joh", 1))
BOOKS.append(Book("Jud", 1))
BOOKS.append(Book("Offb", 22))